export const SET_CURRENT_ACTIVITY = "SET_CURRENT_ACTIVITY";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const UPDATE_ACTIVITIES = "UPDATE_ACTIVITIES";
export const LOADING = "LOADING";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";